### ISSUE TITLE
artifacts in screen manjaro

### ISSUE THREAD

**Issue by LegacyGamerHD** [ChristopherHX/mcpelauncher-manifest#12]
it happens with nvidia gpu
![Schermafdruk van 2019-12-09 18-36-43](https://user-images.githubusercontent.com/25864932/70458738-06933400-1ab3-11ea-82d8-4fc3b74323ca.png)

**Comment by LegacyGamerHD** [comment]
bedrock version 1.13

**Comment by thijs** [comment]
I have the same on Ubuntu Bionic with nvidia card...

Also, I don't seem to be able to play fullscreen and the resolution is way too low (maybe due to that)?

**Comment by LegacyGamerHD** [comment]
@thijs that's because of a 4k monitor and how launcher manage hidpi displays

**Comment by LegacyGamerHD** [comment]
That it's to small in fullscreen

**Comment by ChristopherHX** [comment]
I wasn't aware that the content scaling (sizing) is bugged on Linux too (maybe another nvidia driver Bug). (I fixed enter fullscreen (F11) handling a while ago)
Hidpi problems were only known to me on MacOs (another story)
I made today a special [Appimage](https://github.com/ChristopherHX/linux-packaging-scripts/releases/tag/52.appimage.angle) which using a third party Graphics middleware named [angle](http://angleproject.org/)
Please Test it, I don't know if this library avoid these driver Bugs

**Comment by thijs** [comment]
How do I use/run an Appimage on Ubuntu?

**Comment by NerduMiner** [comment]
Just tested this new Appimage on Linux Mint 19.2 with a Geforce 1050Ti running the 430.50 drivers. There seems to be a bit of change in the initial loading screen and menu, but the original problems are still there.
![MinecraftBedrockForkComparison](https://user-images.githubusercontent.com/23490112/70583309-56452e80-1b8b-11ea-9dfd-66b9f0e8557b.png)
On the left is the 48.bionic build running through a shell script. On the right is the new Appimage build. I noticed that the Appimage build automatically appended the skin for my account, which is something that the 48.bionic build doesn't usually do.

**Comment by Mhowser** [comment]
@thijs right click on the appimage file, properties > permissions > enable executing as a program. Then you can just double click it to start it.

**Comment by thijs** [comment]
Thanks Mhowser. I'll try that, but it might be in vain, seeing NerduMiners comment...

**Comment by thijs** [comment]
It does work. And F11 switches it to fullscreen, which is great.
Sadly, the artifacts are even worse fullscreen. The menu block in the center of the screen is fully covered and unreadable. It does seem as if moving the mouse triggers it. If I don't touch it, the screen renders in correctly, then if I touch the mouse, it devolves into shimmering artifacts.
The resolution is also annoying. Everything is too large on the screen.

**Comment by ChristopherHX** [comment]
I'm going to install Linux amd64 on my old Laptop (2012, it's overheating on *nix, windows works well), but it has an lowend Nvidia 620M GPU.
To see if my old Laptop have comparable Graphics issues with the nvidia drivers...to find eventually a fix...

**Comment by Mhowser** [comment]
@ChristopherHX would you accept hardware donations?

**Comment by ChristopherHX** [comment]
Yes maybe, but I'm not using it as my primary PC as I have a far more powerfull one, but it cannot repoduce nvidia driver Issues ( I skipped adding an dedicated Graphics card as Intel UHD is enough for me )...

**Comment by NerduMiner** [comment]
I was able to reproduce the issue on my desktop with a GTX 1060 running 435.21 graphics drivers. They are slightly different, and the initial loading screen renders a bit of the desktop as well but the main problems are still there as well.
![BedrockLauncherGraphicsArtifacts](https://user-images.githubusercontent.com/23490112/70660877-1a64a480-1c31-11ea-88fb-48d5260389d6.png)
It sounds like these kinds of issues only happen with nvidia graphics cards, do the artifacts also appear on AMD cards or Intel Integrated Graphics?

**Comment by edward3h** [comment]
I'm not sure if I have exactly the right match for this issue but I did a source build last night. I'm running Ubuntu 18.04 and I have Intel Integrated graphics. I was able to run Minecraft 1.14.0 with no graphics problems.

**Comment by ChristopherHX** [comment]
@edward3h As you said you used intel graphics,
only nvidia graphics drivers have issues with my changes, you aren't affected at all by this issue.

**Comment by edward3h** [comment]
Yeah I was just following up on NerduMiner's question about whether other cards were seeing the issues. Sorry if that caused confusion.

**Comment by ChristopherHX** [comment]
**Bad News** even with my old nvidia (optimus) GT620M (2012) **no graphical issus** with the proprietary Graphics drivers from Nvidia 390 (last supported driver, ubuntu 18.04)
I'm unable to fix this issue at all, **help wanted**

Please add your used (nvidia) driver and hardware to your posts

**Comment by TheRealKizu** [comment]
Here: GeForce 940MX/PCIe/SSE2 v: 4.6.0 NVIDIA 430.50

**Comment by CollinScripter** [comment]
Card: GeForce GTX 970
Driver: NVIDIA 435.21
Interestingly enough, at one point it started to "infect" other parts of my UI (KDE). It was minimized and restoring it fixed the "infected" UI, although Minecraft still had the issue.

**Comment by i-use-arch-btw** [comment]
Card: ASUS GTX 1050 Ti
Driver: NVIDIA 440.44
Interestingly enough, during my last testing, the artifacts don't seem to appear on wayland.

**Comment by TheGlitch76** [comment]
I've noticed something about different compositors affecting the amount of artifacts.
Default XFCE has much more artifacts on my GTX 1660 on Arch Linux compared to picom (formally compton) on i3 with the following flags:
`picom --backend glx --glx-no-stencil --glx-no-rebind-pixmap --glx-swap-method exchange --glx-paint-on-overlay --vsync drm` These settings are just what I use to reduce screen tearing, I have no idea what settings exactly affect it.
The difference is between not being able to use the hotbar to few artifacts that "refresh" (?) more often.

**Comment by notnotme** [comment]
Run the game using
`$__GL_IgnoreInvalidateFramebuffer=1 mcpelauncher-client -dg ~/.local/share/mcpelauncher/versions/1.14.1.5/`

Then profit.

**Comment by LegacyGamerHD** [comment]
not a every day sulution @notnotme

**Comment by LegacyGamerHD** [comment]
and it doesnt work on some distros

**Comment by notnotme** [comment]
@LegacyGamerHD This fix should workd on any distro as long as you use the nvidia driver > 418.30 beta.
More information here: https://devtalk.nvidia.com/default/topic/1043953/linux/garbled-up-graphics-in-unity-opengl-/post/5303297/

This is unity related, but it seem to be more or less the same problem. It could be a every day solution if the launcher let the user to put a command line to be happended to the client when started.

**Comment by NerduMiner** [comment]
I can confirm the rule works on my laptop, there are no more screen artifacts.
![image](https://user-images.githubusercontent.com/23490112/71539303-39895480-2908-11ea-93c2-c8590aa2b254.png)

**Comment by blastermaster77** [comment]
> I can confirm the rule works on my laptop, there are no more screen artifacts.
> ![image](https://user-images.githubusercontent.com/23490112/71539303-39895480-2908-11ea-93c2-c8590aa2b254.png)
> EDIT: This was the machine that I produced the first images of when I was comparing the appimage and the version installed through deb packages

can you please explain in detail how to configure that on the nvidia control panel? please

**Comment by NerduMiner** [comment]
@blastermaster77 I didn't have to use the nvidia control panel, it's an argument for when you launch the client through the terminal

**Comment by notnotme** [comment]
@blastermaster77 I try to explain, but the NVIDIA control panel is very tricky to use to me. Screenshots may be better.

- Select "**Application Profile**" then click "**+**" and from here you should be able to create a new profile and a new rule (picture A).
- Try to replicate my screens, **you does not have to modify "source file"**, as it should be already be good (picture B,C).
- When adding a new custom rule (IgnoreInvalidateFramebuffer in this case), you will be warned that this flag is not supported, **ignore the warning and save the configuration** (picture C).
- Don't forget to **save change** using the button in the bottom right of the main NVIDIA control panel after editingthe rules or profiles (picture A).

Hope it help.

A
![A](https://user-images.githubusercontent.com/3787595/71751941-8b3c5c80-2e7d-11ea-933f-f04a7e44a9e8.png)

B
![B](https://user-images.githubusercontent.com/3787595/71751942-8b3c5c80-2e7d-11ea-9bee-ad2989e9e94e.png)

C
![C](https://user-images.githubusercontent.com/3787595/71751943-8b3c5c80-2e7d-11ea-834d-e2092a11cd7f.png)

**Comment by blastermaster77** [comment]
thanks it worked ! yay! thank you very much

**Comment by ChristopherHX** [comment]
Actually I found the difference, my Fork usually calls `glInvalidateFramebuffer` , but minecraft-linux never calls it (obviously called via Minecraft).
Now `glInvalidateFramebuffer`  seems to cause outside of the android world with nvidia drivers, rendering errors. :thinking:
The workaround within this issue is ignoring `glInvalidateFramebuffer`, can also be stubbed within the launcher... (should be the same result)
